CREATE TABLE IF NOT EXISTS Genre (
  ID_Genre SERIAL PRIMARY KEY,
	Name_Genre VARCHAR(80) NOT NULL,
);

CREATE TABLE IF NOT EXISTS Singer (
	ID_Genre INTEGER PRIMARY KEY REFERENCES Genre(ID_Genre),
	ID_Singer SERIAL NOT NULL,
	Name_Singer VARCHAR(80) NOT NULL,
);

CREATE TABLE IF NOT EXISTS Album (
	ID_Singer INTEGER PRIMARY KEY REFERENCES Singer(ID_Singer),
	ID_Album SERIAL NOT NULL,
	Name_Album VARCHAR(80) NOT NULL,
	Year INT(4) NOT NULL
);

CREATE TABLE IF NOT EXISTS Track (
	ID_Album INTEGER PRIMARY KEY REFERENCES Album(ID_Album),
	ID_Track SERIAL NOT NULL,
	Name_Track VARCHAR(80) NOT NULL,
	Duration FLOAT
);

